### ISSUE TITLE
null pointer exception when clicking the date at the top of the main_activity

### ISSUE THREAD

**Issue by jonasrob** [Google-IO-Extended-Grand-Rapids/conference_android#9]
Getting following error after clicking the Date at the top of the activity.

```
 Caused by: java.lang.NullPointerException
            at com.sagetech.conference_android.app.ui.activities.EventDetailActivity.updateScreen(EventDetailActivity.java:67)
            at com.sagetech.conference_android.app.ui.activities.EventDetailActivity.onCreate(EventDetailActivity.java:59)
            at android.app.Activity.performCreate(Activity.java:5586)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at androi
```

**Comment by chenry** [comment]
@KyletheWolff with the recent changes that were just merged into develop, I don't think that this is a concern anymore.  I did hear that you had a good time working with @jonasrob and @adamsova over the weekend though.  That is awesome.  

There is another one that we are going to put your name on.  I think it is a medium level effort.  There is also a low level effort that may tickle your fancy as well.
